rabbit:
  default-endpoint-name: standalone
  endpoints:
    standalone:
      host: localhost
      port: 5672
      managementPort:

logging.level.root: INFO

wes:
  url: http://localhost:9090/runs

spring:
  application:
    name: wgn-dev

node:
  jsonConfigPath: example-node-config.json
