rabbit:
  default-endpoint-name: standalone
  endpoints:
    standalone:
      host: localhost
      port: 5672
      managementPort:

logging.level.root: INFO

rdpc:
  url: http://localhost:4000/graphql

spring:
  application:
    name: wgn-dev

node:
  localSchemaPath: schema/WorkflowParamsTest.avsc
  jsonConfigPath: example-node-config.json

dev:
  exchange: ""
  event:
    analysisId: ""
    analysisState: ""
    analysisType: ""
    studyId: ""
    experimentalStrategy: ""

---
spring:
  profiles: registry

rabbit:
  default-endpoint-name: standalone
  endpoints:
    standalone:
      host: localhost
      port: 5672
      managementPort:
  schema:
    registryURL: http://localhost:8990

node:
  jsonConfigPath: example-node-config.json