
rabbit:
  default-endpoint-name: standalone
  endpoints:
    standalone:
      host: localhost
      port: 5672
      managementPort:

logging.level.root: INFO

workflow:
  url: https://github.com/andricDu/nf-echo-params.git
  service:
    execution.url: http://localhost:9090/runs
    query.url: localhost:5000

spring:
  application:
    name: wgn-dev

pipes:
  queue:
    exchange: "ingest"
    queue: "queued"
  running:
    exchange: "state"
    queue: "running"
  complete:
    exchange: "complete"
    queue: "default.complete"
