

rabbit:
  default-endpoint-name: standalone
  endpoints:
    standalone:
      host: localhost
      port: 5672
      managementPort:

logging.level.root: INFO

workflow:
  url: https://github.com/andricDu/nf-echo-params.git
  service:
    execution.url: http://localhost:9090/runs
    query.url: localhost:5000
