rabbit:
  default-endpoint-name: standalone
  endpoints:
    standalone:
      host: localhost
      port: 5672
      managementPort:

logging.level.root: INFO

rdpc:
  url: https://api.rdpc-dev.cancercollaboratory.org/graphql

spring:
  application:
    name: wgn-dev

node:
  jsonConfigPath: example-node-config.json
