rabbit:
  default-endpoint-name: standalone
  endpoints:
    standalone:
      host: localhost
      port: 5672
      managementPort:

logging.level.root: INFO

workflow:
  service:
    execution.url: http://localhost:9090/runs
    query.url: localhost:5000

spring:
  application:
    name: wgn-dev

node:
  jsonConfigPath: example-node-config.json
